# Generated by Django 5.2.17 on 2026-10-04 12:37

import django.core.validators
import django.db.models.deletion
import pdf_manage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(blank=True, help_text='URL に使う任意の識別子。未入力の場合は UUID だけで参照する。', max_length=100, null=True, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'PDF ドキュメント',
                'verbose_name_plural': 'PDF ドキュメント',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(editable=False, verbose_name='バージョン')),
                ('file', models.FileField(upload_to=pdf_manage.models.pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF ファイル')),
                ('original_filename', models.CharField(editable=False, max_length=255, verbose_name='元のファイル名')),
                ('file_size', models.PositiveBigIntegerField(editable=False, verbose_name='ファイルサイズ')),
                ('checksum', models.CharField(editable=False, max_length=64, verbose_name='SHA-256')),
                ('note', models.TextField(blank=True, verbose_name='変更メモ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pdf_manage.pdfdocument', verbose_name='ドキュメント')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': 'PDF バージョン',
                'verbose_name_plural': 'PDF バージョン',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='MCP が配信するバージョン。切り替えると過去の版に戻せる。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pdf_manage.pdfversion', verbose_name='公開バージョン'),
        ),
        migrations.AddConstraint(
            model_name='pdfversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='pdf_manage_unique_version_per_document'),
        ),
    ]
